---
- name: Update apt cache
  apt:
    update_cache: true

- name: Upgrade the system
  apt:
    upgrade: dist

- name: Install common packages
  apt:
    name:
      - git
      - curl
      - htop
      - wget
      - unzip
      - vim
    state: present

- name: Set timezone
  timezone:
    name: Asia/Dubai

- name: Create a user named mohannad
  user:
    name: mohannad
    shell: /bin/bash
    groups: sudo
    append: true
    create_home: true

- name: Set authorized key for mohannad
  authorized_key:
    user: mohannad
    state: present
    key: "{{ lookup('file', '/home/mohannad/.ssh/id_rsa_vagrant.pub') }}"

- name: Set password for root
  user:
    name: root
    password: "{{ plain_root_password | password_hash('sha512') }}"
  when: plain_root_password is defined

- name: Set password for mohannad
  user:
    name: mohannad
    password: "{{ plain_mohannad_password | password_hash('sha512') }}"
  when: plain_mohannad_password is defined

- name: Check if swap is already enabled
  command: swapon --show
  register: swap_status
  changed_when: false

- name: Create swap file with dd (1GB)
  command: dd if=/dev/zero of=/swapfile bs=1M count=1024
  when: swap_status.stdout == ""
  args:
    creates: /swapfile

- name: Set correct permissions on swap file
  file:
    path: /swapfile
    mode: "0600"
  when: swap_status.stdout == ""

- name: Format the file for swap
  command: mkswap /swapfile
  when: swap_status.stdout == ""

- name: Enable the swap file
  command: swapon /swapfile
  when: swap_status.stdout == ""

- name: Add swap to /etc/fstab
  mount:
    name: none
    src: /swapfile
    fstype: swap
    opts: sw
    state: present
  when: swap_status.stdout == ""
